/*
 * A device API for the Blue Robotics Ping Echosounder
 *
 *~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!
 * THIS IS AN AUTOGENERATED FILE
 * DO NOT EDIT
 *~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!
 *
 */

#pragma once

#include <ping-device.h>

class Ping360 : public PingDevice
{
public:
  /**
   *  @brief Constructor
   *
   *  @param ser: The device I/O
   */
  Ping360(PingPort& port) : PingDevice(port) {}

  /**
   * @brief Destructor
   */
  ~Ping360();

  /**
   *  @brief Establish communications with the device, and initialize the update interval
   *
   *  @param pingIntervalMs: The interval (in milliseconds) between acoustic measurements
   *
   *  @return true if the device was initialized successfully
   */
  bool initialize(uint16_t pingIntervalMs = 50);

  // Device type. 0: Unknown; 1: Echosounder
  uint8_t device_type = 0;

  // Device model. 0: Unknown; 1: Ping360
  uint8_t device_model = 0;

  // Firmware version major number.
  uint16_t firmware_version_major = 0;

  // Firmware version minor number.
  uint16_t firmware_version_minor = 0;

  // The 5V rail voltage.
  uint16_t voltage_5 = 0;

  // The speed of sound in the measurement medium. ~1,500,000 mm/s for water.
  uint32_t speed_of_sound = 0;

  // The beginning of the scan range in mm from the transducer.
  uint32_t scan_start = 0;

  // The length of the scan range.
  uint32_t scan_length = 0;

  // 0: manual mode, 1: auto mode
  uint8_t mode_auto = 0;

  // The minimum interval between acoustic measurements. The actual interval may be longer.
  uint16_t ping_interval = 0;

  // The current gain setting. 0: 0.6, 1: 1.8, 2: 5.5, 3: 12.9, 4: 30.2, 5: 66.1, 6: 144
  uint32_t gain_setting = 0;

  // Acoustic pulse duration.
  uint16_t transmit_duration = 0;

  // Distance to the target.
  uint32_t distance = 0;

  // Confidence in the distance measurement.
  uint8_t confidence = 0;

  // The pulse/measurement count since boot.
  uint32_t ping_number = 0;

  // The temperature in centi-degrees Centigrade (100 * degrees C).
  uint16_t processor_temperature = 0;

  // The temperature in centi-degrees Centigrade (100 * degrees C).
  uint16_t pcb_temperature = 0;

  // The state of the acoustic output. 0: disabled, 1:enabled
  uint8_t ping_enabled = 0;

  // An array of return strength measurements taken at regular intervals across the scan region.
  uint16_t profile_data_length = 0;
  uint8_t* profile_data = 0;


private:
  /**
   *  @brief Handle an incoming message from the device. Internal values are updated according to the device data.
   *
   *  @param message: A pointer to the message received from the device
   */
  void _handleMessage(const ping_message* message) override;
};